---
title: "Advanced Regression Midterm Spring 2024"
author: "Tyler George"
date: "1/25/2024"
output: pdf_document
fig_height: 3
options: \renewcommand{\a}{\alpha} 
---

# Instructions
- This is an open book and note exam. You *cannot* use another students notes or scripts, talk to others about the exam, or use the internet (other than to get the exam/data) 
- If you have questions email me right away.
- Submit via the Github Repo
- You solution should be written as a report. This means that I should be able to read through it and see your evidence that you are discussing. You can quickly add "Figure a" under a plot to reference it. This is most easily done through either word (copying plots or tables from R) or RMarkdown (with a working knitted file). You need to also need to submit your code but I will be evaluating the report, not the code used to make the tables/plots. 


# The Question 
A researcher in geriatrics designed a prospective study to investigate the effects of two interventions on the frequency of falls. One hundred subjects were randomly assigned to one of the two interventions: education only ($X_I = 0$) and education plus aerobic exercise training ($X_I = 1$). Subjects were at least 65 years of age and in reasonably good health.

Three other variables considered to be important as *control* variables were 

- Sex ($X_2: 0=$ female, $1 =$ male)
- Balancing index ($X_3$), the higher the balancing index the more stable the subject
- Strength index ($X_4$), the higher the strength index, the stronger the patient

Each subject kept a diary recording the number of falls, $Y$, during the six month study. The data is named "geriatric.csv." 

Build a model for predicting and understanding the number of falls of a patient using any of the included variables. Make sure to conduct thorough EDA and discuss all plots and tables needed to understand your variables. Make sure to consider both all appropriate types of poisson and linear regression. To goal is for you to exhibit what you know.


